"""
WAF / CDN Detection Module
Identifies web application firewalls and CDN providers from headers and response patterns
"""
import logging
from typing import Any

from modules.common import fetch, make_client

logger = logging.getLogger(__name__)

TIMEOUT = 10

# (name, category, header_signatures, body_signatures, status_codes)
WAF_SIGNATURES: list[dict] = [
    {
        "name": "Cloudflare",
        "category": "CDN/WAF",
        "headers": {"server": ["cloudflare"], "cf-ray": None, "cf-cache-status": None},
        "body": ["cloudflare", "__cf_bm", "cf_clearance"],
        "status_on_block": [403, 429, 503],
    },
    {
        "name": "AWS CloudFront",
        "category": "CDN",
        "headers": {"x-amz-cf-id": None, "via": ["cloudfront"], "x-amz-cf-pop": None},
        "body": ["generated by cloudfront"],
        "status_on_block": [403],
    },
    {
        "name": "Akamai",
        "category": "CDN/WAF",
        "headers": {"x-akamai-transformed": None, "x-check-cacheable": None, "server": ["akamaighost", "akamai"]},
        "body": ["akamai", "reference #"],
        "status_on_block": [403],
    },
    {
        "name": "Imperva / Incapsula",
        "category": "WAF",
        "headers": {"x-iinfo": None, "x-cdn": ["incapsula"]},
        "body": ["incapsula incident", "incap_ses"],
        "status_on_block": [403],
    },
    {
        "name": "Fastly",
        "category": "CDN",
        "headers": {"x-fastly-request-id": None, "via": ["varnish", "fastly"], "x-served-by": None},
        "body": ["fastly error: unknown domain"],
        "status_on_block": [503],
    },
    {
        "name": "Sucuri",
        "category": "WAF",
        "headers": {"x-sucuri-id": None, "server": ["sucuri/cloudproxy"]},
        "body": ["sucuri website firewall", "access denied - sucuri"],
        "status_on_block": [403],
    },
    {
        "name": "ModSecurity",
        "category": "WAF",
        "headers": {"server": ["mod_security", "modsecurity"]},
        "body": ["mod_security", "not acceptable", "406 not acceptable"],
        "status_on_block": [403, 406],
    },
    {
        "name": "F5 BIG-IP ASM",
        "category": "WAF",
        "headers": {"x-wa-info": None, "server": ["bigip"]},
        "body": ["the requested url was rejected", "f5 networks"],
        "status_on_block": [403],
    },
    {
        "name": "AWS WAF",
        "category": "WAF",
        "headers": {"x-amzn-requestid": None},
        "body": ["request blocked", "aws waf"],
        "status_on_block": [403],
    },
    {
        "name": "Vercel",
        "category": "CDN/Hosting",
        "headers": {"x-vercel-id": None, "server": ["vercel"]},
        "body": [],
        "status_on_block": [],
    },
    {
        "name": "Netlify",
        "category": "CDN/Hosting",
        "headers": {"server": ["netlify"], "x-nf-request-id": None},
        "body": [],
        "status_on_block": [],
    },
    {
        "name": "Nginx",
        "category": "Web Server",
        "headers": {"server": ["nginx"]},
        "body": ["nginx"],
        "status_on_block": [],
    },
    {
        "name": "Apache",
        "category": "Web Server",
        "headers": {"server": ["apache"]},
        "body": ["apache"],
        "status_on_block": [],
    },
]


def _check_waf(headers: dict, body: str, status_code: int) -> list[dict]:
    detected = []
    headers_lower = {k.lower(): v.lower() for k, v in headers.items()}
    body_lower = body[:5000].lower()

    for sig in WAF_SIGNATURES:
        score = 0
        matched = []

        for header, values in sig["headers"].items():
            if header in headers_lower:
                if values is None:
                    score += 2
                    matched.append(f"header:{header}")
                else:
                    for v in values:
                        if v in headers_lower[header]:
                            score += 3
                            matched.append(f"header:{header}={v}")

        for body_str in sig["body"]:
            if body_str in body_lower:
                score += 2
                matched.append(f"body:{body_str[:30]}")

        if score >= 2:
            detected.append({"name": sig["name"], "category": sig["category"], "confidence": min(100, score * 20), "signals": matched})

    return detected


def run(domain: str) -> dict[str, Any]:
    findings: list[str] = []
    detected: list[dict] = []
    risk = "low"

    # Normal request
    with make_client(timeout=TIMEOUT) as client:
        for scheme in ("https", "http"):
            url = f"{scheme}://{domain}"
            try:
                resp = fetch(url, client=client,
                             headers={"User-Agent": "Mozilla/5.0 (compatible; DumbAuditor/1.0)"})
                if resp.status_code < 500:
                    cands = _check_waf(dict(resp.headers), resp.text, resp.status_code)
                    for c in cands:
                        if c not in detected:
                            detected.append(c)
                    break
            except Exception:
                continue

        # Send a probing request with SQLi-like payload to trigger WAF block page
        probe_url = f"https://{domain}/?id=1'%20OR%201=1--"
        try:
            probe = fetch(probe_url, client=client)
            cands = _check_waf(dict(probe.headers), probe.text, probe.status_code)
            for c in cands:
                already = next((d for d in detected if d["name"] == c["name"]), None)
                if already:
                    already["confidence"] = min(100, already["confidence"] + c["confidence"] // 2)
                    already["signals"] = list(set(already["signals"] + c["signals"]))
                else:
                    detected.append(c)
        except Exception:
            pass

    # Sort by confidence
    detected.sort(key=lambda x: x["confidence"], reverse=True)

    waf_found = [d for d in detected if d["category"] in ("WAF", "CDN/WAF")]
    cdn_found = [d for d in detected if d["category"] == "CDN"]
    server_found = [d for d in detected if d["category"] == "Web Server"]

    if not waf_found and not cdn_found:
        findings.append("No WAF or CDN detected — origin server may be directly exposed")
        risk = "medium"
    else:
        for w in waf_found:
            findings.append(f"WAF detected: {w['name']} (confidence {w['confidence']}%)")

    return {
        "status": "ok",
        "detected": detected,
        "waf_found": bool(waf_found),
        "cdn_found": bool(cdn_found),
        "waf_names": [d["name"] for d in waf_found],
        "cdn_names": [d["name"] for d in cdn_found],
        "server_names": [d["name"] for d in server_found],
        "risk": risk,
        "findings": findings,
    }
